# Generated by Django 6.0.5 on 2026-05-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_forumthread_forumpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='read_history',
            field=models.ManyToManyField(blank=True, related_name='read_history_profiles', to='news.news'),
        ),
    ]
