# Generated by Django 6.0.5 on 2026-06-01 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_profile_read_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='thread_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='thread_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
