# Generated by Django 6.0.1 on 2026-02-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
