# Generated by Django 6.0.5 on 2026-06-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_forumthread_downvotes_forumthread_upvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='category',
            field=models.CharField(default='Ostatní', max_length=50),
        ),
    ]
