# Generated by Django 6.0.5 on 2026-06-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_forumthread_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
