# Generated by Django 6.0.5 on 2026-06-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_forumthread_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsssource',
            name='weight',
        ),
        migrations.AddField(
            model_name='rsssource',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='rsssource',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Kategorie (např. IT, Sport)'),
        ),
        migrations.AlterField(
            model_name='rsssource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název zdroje (např. iDNES)'),
        ),
        migrations.AlterField(
            model_name='rsssource',
            name='url',
            field=models.URLField(verbose_name='RSS URL'),
        ),
    ]
