# Generated by Django 6.0.5 on 2026-06-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_rsssource_weight_rsssource_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsssource',
            options={'verbose_name': 'RSS Zdroj', 'verbose_name_plural': 'RSS Zdroje'},
        ),
        migrations.AddField(
            model_name='rsssource',
            name='tag_mapping',
            field=models.TextField(blank=True, help_text='Formát: tag_z_rss:interni_kategorie, oddělené čárkou (např. python:IT, uefa:Sport)', verbose_name='Mapování tagů'),
        ),
        migrations.AddField(
            model_name='rsssource',
            name='weight',
            field=models.IntegerField(default=5, verbose_name='Váha / Důvěryhodnost (1-10)'),
        ),
        migrations.AlterField(
            model_name='rsssource',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Výchozí kategorie'),
        ),
        migrations.AlterField(
            model_name='rsssource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název zdroje'),
        ),
    ]
