# Generated by Django 6.0.5 on 2026-06-01 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_rsssource_options_rsssource_tag_mapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='thread',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='category',
            field=models.CharField(db_index=True, default='Ostatní', max_length=50),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
